name: project cicd flow
on:
  push:
    branches:
      -  "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'adopt'
      - name: setup Maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 3.8.2
      - name: run compile
        run: mvn clean install